sudo: false

language: python

python:
    - "2.7.12"
    
before_install:
    - pip install --upgrade pip
    
install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    
before_script:
    - uname -a
    - printenv | sort
    - make versions
    
script:
    - date
    - ls -al
    - make test
