sudo: false

language: python

python:
    - "3.5"
    
before_install:
    - pip3 install --upgrade pip
    
install:
    - pip3 install -r requirements.txt
    
before_script:
    - uname -a
    - printenv | sort
    - make versions
    
script:
    - date
    - ls -al
    - make test
